{
 "title": "Zabbix Server Master Dashboard",
 "tags": [ "zabbix" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Zabbix Agent Ping Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Zabbix agent ping" },
     "itemTag": { "filter": "Application: Monitoring agent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Linux Servers Free disk space on /",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "itemTag": { "filter": "Application: Filesystems" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Physical Processors Consumed",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "AIX" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "CPU number of physical processors consumed"
     },
     "itemTag": { "filter": "Application: CPU" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "AIX Server Problems",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "AIX" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Linux Servers Problems",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Users Logged In",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "AIX" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Number of logged in users" },
     "itemTag": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "severity",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Linux Servers; Inbound traffic on eth0",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Interface eth0: Bits received" },
     "itemTag": { "filter": "Application: Interface eth0" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}