name: Deploy Grafana Container

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check docker-compose
        run: |
          if [ -x "$(command -v docker-compose)" ]; then
            sudo docker-compose version
            echo "docker-compose verified"
          else
            echo "Installing docker-compose"
            sudo yum install -y podman-docker
            sudo curl -SL https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi
      - name: build container and run
        run: |
          sudo docker-compose up


        
